# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish Release  # 工作流名称

on:
  push:
    branches:
      - main  # 当代码推送到master分支时触发工作流程

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # 在最新的Ubuntu操作系统上运行任务

    steps:
      - uses: actions/checkout@v3  # 使用GitHub官方的checkout action，用于检出代码库

      - name: Set up JDK  # 设置JDK
        uses: actions/setup-java@master  # 使用GitHub官方的setup-java action，用于安装和配置Java环境
        with:
          java-version: 8
          distribution: "adopt"
          cache: maven

      - name: Build with Maven  # 使用Maven构建项目
        run: mvn package --batch-mode  # 执行mvn package命令进行项目构建

      - name: Create Release Tag
        id: create_tag
        run: |
          TAG_NAME=v2.3.2.${{ github.run_number }}
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: /web/target/SpringReport.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
          release_notes: |
            Changes in this Release:
            - Add SpringReport.jar