# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish Release  # 工作流名称

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Build
        run: mvn -B clean package -DskipTests

      - name: Generate Tag
        id: tag
        run: |
          # 基于提交哈希生成唯一标签
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG_NAME="v2.3.2-$SHORT_SHA"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          files: |
            /web/target/SpringReport.jar
            README.md
          body: |
            Automated release for tag ${{ steps.tag.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}