# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish Release  # 工作流名称

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR File
        run: |
          # 检查 JAR 是否存在
          if [ ! -f "web/target/SpringReport.jar" ]; then
            echo "Error: JAR file not found!"
            exit 1
          fi

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +%Y%m%d%H%M)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: web/target/*.jar  # 使用通配符
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          name: "Release ${{ steps.create_tag.outputs.TAG_NAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}